apiVersion: apps/v1
kind: Deployment
metadata:
  name: backoffice-app
spec:
  selector:
    matchLabels:
      app: backoffice-app
  template:
    metadata:
      labels:
        app: backoffice-app
    spec:
      imagePullSecrets:
      - name: secret-private-registry
      containers:
      - name: backoffice-app
        image: adhithia21/backoffice-app:5 # {"$imagepolicy": "flux-system:backoffice-app"}
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 8080
